server:
  port: 9095
spring:
  application:
    name: jp-gateway
  profiles:
    active: localhostRouter-EurekaWithCB-auth # This will be using Eureka Server with circuit Breaker and Auth
#    active: localhostRouter-EurekaWithCB # This will be using Eureka Server with circuit Breaker
#    active: localhostRouter-withEureka # This will be using Eureka Server
#    active: localhostRouter-noEureka # This will be using by calling: http://localhost:9090/api/v1/dragonball/names

#logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
#  tracing:
#    sampling:
#      #      used for tracing
#      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true