server:
  port: 9090
spring:
  application:
    name: jp-gateway
  profiles:
    active: localhostRouter-EurekaWithCB
#    active: localhostRouter-withEureka # This will be using Eureka Server
#    active: localhostRouter-noEureka # This will be using by calling: http://localhost:9090/api/v1/dragonball/names

management:
  endpoints:
    web:
      exposure:
        include: '*'